---
- name: Install Node Exporter and run it as a service
  hosts: pis

  tasks:
  - name: Extract the package
    ansible.builtin.unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-{{ arch }}64.tar.gz
      dest: /home/stefan
      creates: /home/stefan/node_exporter-1.4.0.linux-{{ arch }}64/node_exporter
      remote_src: true

  - name: Copy the package to usr/bin
    become: true
    ansible.builtin.copy:
      src: /home/stefan/node_exporter-1.4.0.linux-{{ arch }}64/node_exporter
      dest: /usr/local/bin/node_exporter
      remote_src: true

  - name: Create group for node_exporter
    become: true
    ansible.builtin.group:
      name: node_exporter
      state: present

  - name: Create user for node_exporter
    become: true
    ansible.builtin.user:
      name: node_exporter
      group: node_exporter

  - name: Change file ownership and group for node_exporter
    become: true
    ansible.builtin.file:
      path: /usr/local/bin/node_exporter
      owner: node_exporter
      group: node_exporter
      mode: a+x

  - name: Copy the service file
    become: true
    ansible.builtin.copy:
      src: ./node_exporter.service
      dest: /etc/systemd/system/node_exporter.service

  - name: Force systemd to reload
    become: true
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Make sure node exporter service is running
    become: true
    ansible.builtin.systemd:
      state: started
      name: node_exporter
