---
- name: Update with Apt
  hosts: pis
  become: true

  tasks:
  - name: Update apt-get repo and cache
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    ansible.builtin.apt: upgrade=dist force_apt_get=yes
